# Generated by Django 5.0.3 on 2024-06-28 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namalayanan', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
                ('foto', models.ImageField(default='logo.png', upload_to='media/foto')),
                ('pengerjaan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namastatus', models.CharField(choices=[('Sudah di ACC', 'Sudah di ACC'), ('Belum di ACC', 'Belum di ACC')], default='Belum Di Acc', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('nohp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('nohp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Sedang Bekerja', 'Sedang Bekerja'), ('Tidak Tersedia', 'Tidak Tersedia')], default='Tersedia', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, related_name='staff_users', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tbBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=10, unique=True)),
                ('desk', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(null=True)),
                ('waktu', models.TimeField()),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('namastatus', models.CharField(choices=[('Sudah di ACC', 'Sudah di ACC'), ('Belum di ACC', 'Belum di ACC')], default='Belum di ACC', max_length=15)),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('namalayanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namalayanan_bookings', to='mysalon.tblayanan')),
            ],
        ),
        migrations.CreateModel(
            name='tbProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodestaff', models.CharField(blank=True, max_length=10, unique=True)),
                ('kode', models.CharField(blank=True, max_length=10, unique=True)),
                ('tanggal', models.DateTimeField(null=True)),
                ('waktu', models.TimeField()),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('namalayanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namalayanan_progress', to='mysalon.tblayanan')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='mysalon.staff')),
            ],
        ),
    ]
