# Generated by Django 5.0.3 on 2024-06-29 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0002_customuser_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbprogress',
            name='staff',
        ),
        migrations.AddField(
            model_name='tbprogress',
            name='nama',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Tersedia', to='mysalon.staff'),
        ),
    ]
