# Generated by Django 5.0.3 on 2024-06-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0004_tbprogress_namastatus_alter_tbprogress_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='tbbooking',
            name='nama',
        ),
    ]
