# Generated by Django 5.0.3 on 2024-06-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0005_remove_customuser_staff_remove_tbbooking_nama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbprogress',
            old_name='nama',
            new_name='staff',
        ),
        migrations.AlterField(
            model_name='tbprogress',
            name='namastatus',
            field=models.CharField(choices=[('Sudah di ACC', 'Sudah di ACC'), ('Belum di ACC', 'Belum di ACC')], default='Belum di ACC', max_length=20),
        ),
    ]
