# Generated by Django 5.0.3 on 2024-07-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0006_rename_nama_tbprogress_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbbooking',
            name='namastatus',
            field=models.CharField(choices=[('Sudah di ACC', 'Sudah di ACC'), ('Belum di ACC', 'Belum di ACC'), ('Terselesaikan', 'Terselesaikan'), ('Dibatalkan', 'Dibatalkan')], default='Belum di ACC', max_length=15),
        ),
    ]
