# Generated by Django 5.0.3 on 2024-07-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0009_alter_tbprogress_namastatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbstatus',
            name='namastatus',
            field=models.CharField(choices=[('Sudah di ACC', 'Sudah di ACC'), ('Belum di ACC', 'Belum di ACC'), ('Terselesaikan', 'Terselesaikan'), ('Dibatalkan', 'Dibatalkan')], default='Belum Di Acc', max_length=15),
        ),
    ]
