# Generated by Django 5.0.3 on 2024-07-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0012_rename_user_tbbooking_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbbooking',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='tbbooking',
            name='nohp',
        ),
        migrations.RemoveField(
            model_name='tbbooking',
            name='username',
        ),
        migrations.RemoveField(
            model_name='tbprogress',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbprogress',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='tbprogress',
            name='nohp',
        ),
        migrations.AddField(
            model_name='tbbooking',
            name='namauser',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='tbbooking',
            name='nomoruser',
            field=models.IntegerField(default='0123456789'),
        ),
        migrations.AddField(
            model_name='tbprogress',
            name='namauser',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='tbprogress',
            name='nomoruser',
            field=models.IntegerField(default='0123456789'),
        ),
        migrations.AlterField(
            model_name='tbbooking',
            name='alamat',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='tbprogress',
            name='alamat',
            field=models.TextField(default='Unknown'),
        ),
    ]
