# Generated by Django 5.0.3 on 2024-07-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0013_remove_tbbooking_nama_remove_tbbooking_nohp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbprogress',
            name='nomoruser',
            field=models.IntegerField(default='01234567890'),
        ),
    ]
