# Generated by Django 5.0.3 on 2024-07-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0014_alter_tbprogress_nomoruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbbooking',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbbooking',
            name='namauser',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbbooking',
            name='nomoruser',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbprogress',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbprogress',
            name='namauser',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbprogress',
            name='nomoruser',
            field=models.IntegerField(),
        ),
    ]
