# Generated by Django 5.0.3 on 2024-07-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0015_alter_tbbooking_alamat_alter_tbbooking_namauser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbbooking',
            name='nomoruser',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbprogress',
            name='nomoruser',
            field=models.TextField(),
        ),
    ]
