# Generated by Django 5.0.3 on 2024-07-07 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0016_alter_tbbooking_nomoruser_alter_tbprogress_nomoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
