# Generated by Django 5.0.3 on 2024-07-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0017_tbbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
